# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/Pallinder/go-randomdata"
  version = "~1.1.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.0.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.4.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/kennygrant/sanitize"
  version = "~1.2.4"

[[constraint]]
  branch = "master"
  name = "github.com/mendsley/gojwk"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "~2.2.2"

[[constraint]]
  name = "stash.kopano.io/kc/libkcoidc"
  version = "~0.7.0"

[[constraint]]
  name = "stash.kopano.io/kgol/rndm"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
